# Use the README file as a reference to customize settings.

Rating:
  fields:
    default: value, comment, rating_type
    form: value, comment, rating_type
  relationships: comment, rating_type
  application: Application
